/**
 * modules/insightsEngine.js
 * ---------------------------------------------------------------------------
 * Generates short, plain-language observations from the calculator's own
 * numbers. This is a deterministic, rule-based engine — NOT a live LLM call.
 * (A standalone hosted static site has no backend or API key to call a model
 * with, so "AI insights" here means "insights, generated by rules", not
 * generative text. See the note in app.js / the project README.)
 *
 * Every rule is grounded in a number already computed elsewhere in the app,
 * or in the sourced reference ranges from the "Which efficiency-drop should
 * you use?" table. Nothing here is invented or embellished — the explicit
 * goal (per the product brief) is to never exaggerate.
 *
 * Exposed as window.E20.insights
 */
(function (global) {
  "use strict";

  const fmt = global.E20.format;

  // Classify a mileage-drop percentage against the sourced reference ranges
  // used elsewhere on the page (NITI Aayog roadmap, ARAI 2026 fleet testing).
  function classifyDrop(pct) {
    if (pct <= 2) return { label: "excellent", detail: "in line with vehicles factory-calibrated for E20" };
    if (pct <= 4) return { label: "good", detail: "close to the range NITI Aayog attributes to E20-calibrated two-wheelers" };
    if (pct <= 6) return { label: "typical", detail: "within ARAI's 2026 fleet-testing range for a mixed-age fleet (2–6%)" };
    return { label: "on the higher end", detail: "closer to older, E0-designed engines running on E20 (NITI Aayog: 6–7%)" };
  }

  // context: {
  //   mileageDropPct, extraYearlyCost, extraMonthlyCost, petrolPrice,
  //   monthlyKm, originalMileage, fuelLogAverageMileage (nullable), vehicleName (nullable)
  // }
  // Returns an array of { icon, text } — plain strings, safe to render as text.
  function generate(context) {
    const insights = [];
    const {
      mileageDropPct, extraYearlyCost, extraMonthlyCost, petrolPrice,
      monthlyKm, originalMileage, fuelLogAverageMileage, vehicleName,
    } = context;

    // 1. Where this mileage-drop assumption sits versus sourced ranges.
    const cls = classifyDrop(mileageDropPct);
    insights.push({
      icon: "📊",
      text: "A " + fmt.fmtNum(mileageDropPct, 1) + "% mileage drop is " + cls.label + " for E20 — " + cls.detail + ".",
    });

    // 2. Extra yearly cost, expressed as an equivalent litres figure so the
    // rupee amount has a concrete, checkable anchor.
    if (extraYearlyCost > 0 && petrolPrice > 0) {
      const equivLitres = extraYearlyCost / petrolPrice;
      insights.push({
        icon: "💸",
        text: "At " + fmt.fmtNum(monthlyKm, 0) + " km/month, E20 costs you roughly " + fmt.fmtINR(extraYearlyCost) +
          " extra a year — about the same as " + fmt.fmtNum(equivLitres, 0) + " litres of petrol at today's price.",
      });
    } else {
      insights.push({
        icon: "✅",
        text: "At these numbers, the modelled extra cost from E20 is negligible or zero for your monthly distance.",
      });
    }

    // 3. Per-day framing, for a more everyday sense of scale. Kept modest —
    // explicitly says "small" when it genuinely is, rather than inflating
    // small numbers to sound significant.
    if (extraMonthlyCost > 0) {
      const perDay = extraMonthlyCost / 30;
      const scaleWord = perDay < 10 ? "a small" : perDay < 40 ? "a moderate" : "a fairly noticeable";
      insights.push({
        icon: "🗓️",
        text: "That works out to about " + fmt.fmtINR(perDay) + " a day — " + scaleWord + " addition to your regular fuel spend.",
      });
    }

    // 4. Cross-check against a real fuel log, if the user has logged enough
    // fill-ups to derive one. Only speaks up if the gap is meaningful
    // (>5%), so it doesn't nag over rounding noise.
    if (fuelLogAverageMileage !== null && fuelLogAverageMileage !== undefined && originalMileage > 0) {
      const diffPct = Math.abs(fuelLogAverageMileage - originalMileage) / originalMileage * 100;
      if (diffPct > 5) {
        insights.push({
          icon: "🔍",
          text: "Your logged real-world mileage (" + fmt.fmtNum(fuelLogAverageMileage, 1) + " km/L) differs from the Original Mileage you entered (" +
            fmt.fmtNum(originalMileage, 1) + " km/L) by about " + fmt.fmtNum(diffPct, 0) + "%. Using the logged figure would give a more accurate estimate.",
        });
      } else {
        insights.push({
          icon: "🔍",
          text: "Your logged real-world mileage (" + fmt.fmtNum(fuelLogAverageMileage, 1) + " km/L) is close to the Original Mileage you entered — your estimate looks reliable.",
        });
      }
    }

    // 5. Named-vehicle framing, only when a profile is active — keeps the
    // insight panel feeling attached to a specific vehicle rather than
    // generic, without inventing anything about that vehicle.
    if (vehicleName) {
      insights.push({
        icon: "🚘",
        text: "These figures are calculated for " + vehicleName + ". Switch vehicles above to compare.",
      });
    }

    return insights;
  }

  global.E20 = global.E20 || {};
  global.E20.insights = { generate: generate, classifyDrop: classifyDrop };
})(window);
